---
name: Team sync template
about: Team Sync Template
title: Team sync - {Date}, 2024
labels: ''
assignees: ''
---

Please take a moment to update the [Post PST A11y Audit](https://github.com/orgs/Quansight-Labs/projects/11/views/7) project board.

Then please provide your updates using the following template. (You may have work outside the post-audit tasks, please include that work, too.)

```
- Progress made since last sync, if any
  - 
- Currently working on
  - 
- Blockers, questions, or anything the team can help you with
  - 
- Needs discussion
  - 
- Upcoming PTO 
  - 
- How many hours per week you have allocated to this project/Change in allocation
```

Previous: [{Date}](https://github.com/Quansight-Labs/czi-scientific-python-mgmt/issues/{number})
